config/routes.rb
Rails.application.routes.draw do
 
  resources :categories
  devise_for :users
  
  resources :articles do
    resources :comments, only: [:create, :destroy, :update]
  end


  get 'welcome/index'
  get "special", to: "welcome#"
  root 'welcome#index'

  get 'dashboard', to: "welcome#dashboard"

  put "/articles/:id/publish" , to: "articles#publish"


=begin 
  resources articles:, except: [delete]
  resources articleS:, only: [:create, :show ] 

=end 

=begin
  get "/articles"   index
  post "/articles"  create
  delete "/articles"  delete

  get "/articles/:id"   show
  get "articles/new"   new
  get "articles/:id/edit"   edit
  patch "/articles/:id"   update
  put "/articles/:id"  update
=end
end

app/views/partials/_navigation.html.erb
<header>
<nav class="be-red white largue-padding">
<ul id="menu" class="row center-xs around-xs middle-xs">

<li class="col-md">
<h1 id="logo" class="no-margin"> <%= link_to "Blog Facilito", root_path %> </h1>
</li>	

<li class="col-md">
<%= link_to "Artículos", articles_path %>
</li>

<% @categories.each do |category| %>

<li class="col-md">
<%= link_to category.name, category %> 
</li>
<%end%>	

<% if user_signed_in? %>
<li class="col-md">
 <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
</li>
<%else%>

<li class="col-md">
 <%= link_to "Iniciar sesión", new_user_session_path, method: :get %>
</li>

<li class="col-md">
 <%= link_to "Crear cuenta", new_user_registration_path, method: :get %>
</li>

<%end%>

</ul>	
</nav>
</header>